# Generated by Django 4.2.3 on 2023-11-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_user_alter_mealplan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique recipe'),
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipe',
        ),
    ]
