# Generated by Django 4.2.3 on 2023-12-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_ingredient_title_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique recipe',
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique recipe'),
        ),
    ]
